sudo: required
services: 
  - docker

before_install:
  - docker build -t meghpatel0607/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true meghpatel0607/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend-react"
  env: "Frontend-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-638206784914"
  bucket_path: "frontend-react"
  on:
    brach: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"